# app/docx_exporter.py
"""Build a styled .docx file from Content Cruncher AI results
(summary / flashcards / quiz / mind map)."""

import io
import re
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _add_inline_bold(paragraph, text: str):
    """Add text to a paragraph, honoring **bold** markers."""
    parts = re.split(r"\*\*(.*?)\*\*", text)
    for i, part in enumerate(parts):
        if not part:
            continue
        run = paragraph.add_run(part)
        if i % 2 == 1:
            run.bold = True


def _render_mind_map_lines(node, depth=0, lines=None):
    if lines is None:
        lines = []
    pad = "  " * depth
    if isinstance(node, str):
        lines.append(pad + "• " + node)
    elif isinstance(node, list):
        for n in node:
            _render_mind_map_lines(n, depth, lines)
    elif isinstance(node, dict):
        for k, v in node.items():
            prefix = "◆ " if depth == 0 else "├─ "
            lines.append(pad + prefix + str(k))
            if v:
                _render_mind_map_lines(v, depth + 1, lines)
    else:
        lines.append(pad + str(node))
    return lines


def build_export_docx(title: str, source_label: str, source_type: str, result: dict) -> bytes:
    """Convert AI result dict into a styled .docx and return raw bytes."""
    doc = DocxDocument()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Cover
    title_para = doc.add_paragraph()
    title_run = title_para.add_run("STUDYOS — CONTENT CRUNCHER REPORT")
    title_run.bold = True
    title_run.font.size = Pt(20)
    title_run.font.color.rgb = RGBColor(0x6D, 0x5E, 0xF7)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()

    info_lines = [
        f"Source Type : {source_type.title()}",
        f"Source      : {source_label}",
    ]
    for line in info_lines:
        p = doc.add_paragraph()
        r = p.add_run(line)
        r.italic = True
        r.font.size = Pt(9)
        r.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    doc.add_paragraph()

    # Summary
    if result.get("summary"):
        h = doc.add_heading("Summary", level=1)
        h.runs[0].font.color.rgb = RGBColor(0x0D, 0x47, 0xA1)
        for para in str(result["summary"]).split("\n"):
            para = para.strip()
            if para:
                p = doc.add_paragraph()
                _add_inline_bold(p, para)
        doc.add_paragraph()

    # Flashcards
    if result.get("flashcards"):
        h = doc.add_heading("Flashcards", level=1)
        h.runs[0].font.color.rgb = RGBColor(0x6D, 0x5E, 0xF7)
        for i, fc in enumerate(result["flashcards"], 1):
            q = fc.get("question", "")
            a = fc.get("answer", "")
            p = doc.add_paragraph()
            r = p.add_run(f"Q{i}. {q}")
            r.bold = True
            p2 = doc.add_paragraph()
            r2 = p2.add_run(f"A: {a}")
            r2.font.color.rgb = RGBColor(0x22, 0xC5, 0x5E)
            doc.add_paragraph()

    # Quiz
    if result.get("quiz_questions"):
        h = doc.add_heading("Quiz", level=1)
        h.runs[0].font.color.rgb = RGBColor(0x1E, 0x88, 0xE5)
        for i, q in enumerate(result["quiz_questions"], 1):
            p = doc.add_paragraph()
            r = p.add_run(f"Q{i}. {q.get('question', '')}")
            r.bold = True
            for opt in q.get("options", []):
                op = doc.add_paragraph(style="List Bullet")
                op.add_run(opt)
            ans_p = doc.add_paragraph()
            ans_r = ans_p.add_run(f"Correct Answer: {q.get('correct_answer', '')}")
            ans_r.italic = True
            ans_r.font.color.rgb = RGBColor(0x22, 0xC5, 0x5E)
            doc.add_paragraph()

    # Mind Map
    if result.get("mind_map"):
        h = doc.add_heading("Mind Map", level=1)
        h.runs[0].font.color.rgb = RGBColor(0x22, 0xC5, 0x5E)
        lines = _render_mind_map_lines(result["mind_map"])
        for line in lines:
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.font.name = "Consolas"
            run.font.size = Pt(10)
        doc.add_paragraph()

    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run("Generated by StudyOS Content Cruncher")
    footer_run.italic = True
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
